name: tetoris
description: Teto Falling Blocks game.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/game.html
